//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA2B+pw1SPMUqTDRyjMnk3mQAAAAACAAAAAAAQZgAAAAEAACAAAAArXgs8eFIT07pfn01aL0kVTn/SJqDMFjn0fp6/1BnNMAAAAAAOgAAAAAIAACAAAAChejkDI+iSRXm8nD6f1ri18ijdDuCohTww2Kc7p1LdUkAAAADjzUuUcjLtsYoGFFZh29Tj8YFZ4y1snFCxrNZnepENpBVHnvEYLEhwCZa7BX//jxlCizH388kqdKkoZ6Yjc+7+QAAAACWgAsPOQPxAqUMmvVssmk81WrBwqzNZ8dqEE1ATJjb+FLP/QEwoelJmedKMGUaDzQVg0K+XR4lK0+xvn+Jkf9I=")]
        public string Email {
            get {
                return ((string)(this["Email"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAyKIuXEsh+k6DnjTIYBuw8wQAAAACAAAAAAAQZgAAAAEAACAAAABDpTM9hoN2yvQI2PrzVa9BVxisfNYd+oXS9h9aqKpwxwAAAAAOgAAAAAIAACAAAADFE6/y8AmYVn9nJZFsR0bEEjXBJmn+8CF9oV9aq8PFDTAAAACjwXwaleTd9N7DZrQzTG4wPGj7RiPwLxXb0it+ips7cR2t/vvN8cOJwEBTjw9yuKBAAAAAWzVXDNCeCiQ/J+2UxkB+hmm2uM6VFyQMiCvRWQjKju7mh+rHhgCxOrRydGcq4r2sNLCNzms8Ted+gKjkHgJ92w==")]
        public string EmailPassword {
            get {
                return ((string)(this["EmailPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\PizzaAppDB.md" +
            "f;Integrated Security=True")]
        public string PizzaAppDBConnectionString {
            get {
                return ((string)(this["PizzaAppDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=PizzaDB;Integrated Security=True")]
        public string PizzaDBConnectionString {
            get {
                return ((string)(this["PizzaDBConnectionString"]));
            }
        }
    }
}
